package vista;

import controlador.ControladorMetodoAsignacion;
import javax.swing.JTable;

import modelo.ModeloMetodoAsignacion;

/**
 *
 * @author Omega03
 */
public class VistaMetodoAsignacion extends javax.swing.JPanel {

    public JTable tablaDatos;
    public VistaMetodoAsignacion() {
        initComponents();
        modelo.ModeloMetodoAsignacion modelo = new ModeloMetodoAsignacion(this);
        controlador.ControladorMetodoAsignacion controlador = new ControladorMetodoAsignacion(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelProceso = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelResultado = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelTabla = new javax.swing.JPanel();
        txtFilas = new javax.swing.JTextField();
        txtColumnas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGenerarTabla = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1040, 720));
        setMinimumSize(new java.awt.Dimension(1040, 720));
        setPreferredSize(new java.awt.Dimension(1040, 720));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelFondo.setBackground(new java.awt.Color(244, 246, 248));
        panelFondo.setMaximumSize(new java.awt.Dimension(1040, 720));
        panelFondo.setMinimumSize(new java.awt.Dimension(1040, 720));
        panelFondo.setPreferredSize(new java.awt.Dimension(1040, 720));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 246, 248));
        jPanel1.setForeground(new java.awt.Color(27, 38, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("60s Scoreboard", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 59, 85));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Método Asignación");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        panelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        btnCalcular.setBackground(new java.awt.Color(21, 101, 192));
        btnCalcular.setMaximumSize(new java.awt.Dimension(240, 100));
        btnCalcular.setMinimumSize(new java.awt.Dimension(240, 100));
        btnCalcular.setPreferredSize(new java.awt.Dimension(240, 100));
        btnCalcular.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("60s Scoreboard", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CalculaR");
        btnCalcular.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        panelFondo.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 150, 30));

        jLabel3.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 59, 85));
        jLabel3.setText("Columnas:");
        panelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, -1));

        panelProceso.setBackground(new java.awt.Color(244, 246, 248));
        panelProceso.setLayout(new javax.swing.BoxLayout(panelProceso, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelProceso);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 590, 350));

        panelResultado.setBackground(new java.awt.Color(244, 246, 248));
        panelResultado.setLayout(new javax.swing.BoxLayout(panelResultado, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(panelResultado);

        panelFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 380, 160));

        panelTabla.setBackground(new java.awt.Color(244, 246, 248));
        panelTabla.setLayout(new javax.swing.BoxLayout(panelTabla, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(panelTabla);

        panelFondo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 170));

        txtFilas.setBackground(new java.awt.Color(244, 246, 248));
        txtFilas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtFilas.setForeground(new java.awt.Color(36, 59, 85));
        txtFilas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        panelFondo.add(txtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, 30));

        txtColumnas.setBackground(new java.awt.Color(244, 246, 248));
        txtColumnas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(36, 59, 85));
        txtColumnas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        panelFondo.add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 30));

        jLabel4.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 59, 85));
        jLabel4.setText("Resultado:");
        panelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 100, -1));

        jLabel5.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 59, 85));
        jLabel5.setText("Filas:");
        panelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, -1));

        btnGenerarTabla.setBackground(new java.awt.Color(21, 101, 192));
        btnGenerarTabla.setMaximumSize(new java.awt.Dimension(240, 100));
        btnGenerarTabla.setMinimumSize(new java.awt.Dimension(240, 100));
        btnGenerarTabla.setPreferredSize(new java.awt.Dimension(240, 100));
        btnGenerarTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Generar tabla");
        btnGenerarTabla.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        panelFondo.add(btnGenerarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 150, 30));

        add(panelFondo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnCalcular;
    public javax.swing.JPanel btnGenerarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelFondo;
    public javax.swing.JPanel panelProceso;
    public javax.swing.JPanel panelResultado;
    public javax.swing.JPanel panelTabla;
    public javax.swing.JTextField txtColumnas;
    public javax.swing.JTextField txtFilas;
    // End of variables declaration//GEN-END:variables

 public void setControlador(ControladorMetodoAsignacion controlador) {
      this.btnCalcular.addMouseListener(controlador);
      this.btnGenerarTabla.addMouseListener(controlador);
    }
}