/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ControladorMetodoGrafico;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicComboBoxUI;
import modelo.ModeloMetodoGrafico;

/**
 *
 * @author Omega03
 */
public class VistaMetodoSimplex extends javax.swing.JPanel {
 

    public JPanel panelGrafico;

    public VistaMetodoSimplex() {
        initComponents();

        // Inicializar modelo y controlador
 
    }

 

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtZ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCalcularRestricciones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRestricciones = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelTabla1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1040, 720));
        setMinimumSize(new java.awt.Dimension(1040, 720));
        setPreferredSize(new java.awt.Dimension(1040, 720));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        panelFondo.setBackground(new java.awt.Color(244, 246, 248));
        panelFondo.setMaximumSize(new java.awt.Dimension(1040, 720));
        panelFondo.setMinimumSize(new java.awt.Dimension(1040, 720));
        panelFondo.setPreferredSize(new java.awt.Dimension(1040, 720));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 246, 248));
        jPanel1.setForeground(new java.awt.Color(27, 38, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("60s Scoreboard", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 59, 85));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Método SÍMPLEX");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        panelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        cmbTipo.setBackground(new java.awt.Color(244, 246, 248));
        cmbTipo.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        cmbTipo.setForeground(new java.awt.Color(36, 59, 85));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maximizar", "Minimizar" }));
        cmbTipo.setToolTipText("");
        cmbTipo.setBorder(null);
        panelFondo.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 30));
        // quitar borde estándar
        cmbTipo.setBorder(BorderFactory.createEmptyBorder());

        // aplicar solo borde inferior
        //cmbTipo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0x1565C0)));

        // fondo y texto
        cmbTipo.setUI(new javax.swing.plaf.basic.BasicComboBoxUI());
        cmbTipo.setUI(new BasicComboBoxUI() {
            @Override
            public void paintCurrentValueBackground(Graphics g, Rectangle bounds, boolean hasFocus) {
                // Evita que pinte un fondo gris feo
                g.setColor(cmbTipo.getBackground());
                g.fillRect(bounds.x, bounds.y, bounds.width, bounds.height);
            }
        });

        cmbTipo.setUI(new BasicComboBoxUI() {
            @Override
            protected JButton createArrowButton() {
                JButton button = new JButton("▼");
                button.setBorder(BorderFactory.createEmptyBorder());
                button.setContentAreaFilled(false);
                button.setForeground(new Color(36,59,85)); // color de la flecha
                return button;
            }
        });

        txtZ.setBackground(new java.awt.Color(244, 246, 248));
        txtZ.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtZ.setForeground(new java.awt.Color(36, 59, 85));
        txtZ.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        panelFondo.add(txtZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));

        jLabel2.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 59, 85));
        jLabel2.setText("Paso 2 - FORMAM ESTÁNDAR A FORMA SIMPLEX");
        panelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 450, -1));

        txtCalcularRestricciones.setBackground(new java.awt.Color(244, 246, 248));
        txtCalcularRestricciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCalcularRestricciones.setForeground(new java.awt.Color(36, 59, 85));
        txtCalcularRestricciones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        panelFondo.add(txtCalcularRestricciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 600, 30));

        jLabel3.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 59, 85));
        jLabel3.setText("Restricciones");
        panelFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 150, 150, -1));

        txtRestricciones.setBackground(new java.awt.Color(244, 246, 248));
        txtRestricciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtRestricciones.setForeground(new java.awt.Color(36, 59, 85));
        txtRestricciones.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(36, 59, 85)));
        panelFondo.add(txtRestricciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 600, 30));

        jLabel4.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 59, 85));
        jLabel4.setText("Paso 3 - Prueba de optimalidad");
        panelFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 510, -1));

        panelTabla1.setBackground(new java.awt.Color(204, 204, 204));
        panelFondo.add(panelTabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 600, 140));

        jLabel5.setFont(new java.awt.Font("60s Scoreboard", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 59, 85));
        jLabel5.setText("Paso 1 - MODELO LINEAL A FORMAM ESTÁNDAR");
        panelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, -1));

        panelTabla.setBackground(new java.awt.Color(204, 204, 204));
        panelFondo.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 600, 170));

        btnCalcular.setBackground(new java.awt.Color(21, 101, 192));
        btnCalcular.setMaximumSize(new java.awt.Dimension(240, 100));
        btnCalcular.setMinimumSize(new java.awt.Dimension(240, 100));
        btnCalcular.setPreferredSize(new java.awt.Dimension(240, 100));
        btnCalcular.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("60s Scoreboard", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CalculaR");
        btnCalcular.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        panelFondo.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, 30));

        add(panelFondo);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnCalcular;
    public javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelFondo;
    public javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTabla1;
    public javax.swing.JTextField txtCalcularRestricciones;
    public javax.swing.JTextField txtRestricciones;
    public javax.swing.JTextField txtZ;
    // End of variables declaration//GEN-END:variables

   // Si tenés un setControlador, debería estar definido aquí
public void setControlador(ControladorMetodoGrafico controlador) {
    // Como es un JPanel (simulando botón), usamos MouseListener
    this.btnCalcular.addMouseListener(controlador);
}

}
